/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    'Info': '信息',
    'levels to the first 3 Energy Upgrades.': '升级到前 3 次能源升级。',
    'Main': '首页',
    'Mega-Energy': '巨型能源',
    'Options': '选项',
    'Super': '超级',
    'Super Drives': '超级驱动器',
    'Super-Energy': '超级能源',
    'Superchargers': '超级充电器',
    'weaker, and adds': '较弱，并增加',
    'Self-Charging Batteries': '自充电电池',
    ', which adds': '，增加',
    ', which makes Energy Overflow': '，这就产生了能源溢出',
    '\t\tYou have': '\t\t你有',
    '\t\t\tYou have split': '\t\t\你分裂了',
    '\t\t\t\tYour best Energy exponent in an Unfortunate run is': '\t\t\t\t你在不幸运行中的最佳能源指数是',
    '\t\t\t\tYou have': '\t\t\t\t你有',
    'Archaic Processors': '古老的处理器',
    'atoms, which adds': '原子，这增加了',
    'Chargers': '充电器',
    'Currently': '当前',
    'Energy': '能源',
    'Reset Hyper Upgrades': '重置超超级升级',
    'Sacrifice all previous progress to build a Mega Factory.': '牺牲之前的所有进度来建造超级工厂。',
    'and reduce the Mega Energy effect softcap\'s power by': '并通过以下方式降低 巨型能源 效果 软上限 的功率',
    'to all previous Energy exponents.': '到所有以前的能源指数。',
    'to the Energy & Super-Energy exponents.': '到能源和超级能源指数。',
    'to the Fortune Energy exponent.': '到财富能源指数。',
    'to the Hyper-Energy exponent.': '到超超级能源指数。',
    'Hyper-Energy': '超超级能源',
    'Fortune Energy': '财富能源',
    'Galvanic Compressors': '电流压缩机',
    'Gifts, which multiply the Fortune Energy exponent by': '礼物，将财富能源指数乘以',
    'Supercharge your Energy to gain {{formatWhole(tmp.sup.gain)}} base Super-Energy, and to increase the Super-Energy exponent by {{format(tmp.sup.expInc)}}.': '增压你的能源以获得 {{formatWhole(tmp.sup.gain)}} 基础超级能源，并将超级能源指数增加 {{format(tmp.sup.expInc)}}。',
    'You have supercharged your Energy {{formatWhole(player.sup.times)}} times.': '你已经将你的能源增压 {{formatWhole(player.sup.times)}} 次。',
    'WARNING: Each Hyper Upgrade level decreases the Hyper-Energy exponent by {{format(tmp.hyper.upgDecExp)}}. (Currently: -{{format(tmp.hyper.totalUpgs.times(tmp.hyper.upgDecExp))}}': '警告：每个超级升级级别都会将超超级能量指数降低 {{format(tmp.hyper.upgDecExp)}}。 （目前：-{{format(tmp.hyper.totalUpgs.times(tmp.hyper.upgDecExp))}}',
    '\t\t\tYou have': '\t\t\t你有',
    'Due to Energy Overflow, your Energy is being divided by {{format(tmp.en.divPerSec)}} every second.': '由于能量溢出，你的能量每秒被 {{format(tmp.en.divPerSec)}} 分割。',
    '{{formatWhole(tmp.skills[x].xpGain)}} XP (next at {{format(nextXP(x))}} {{skill_data[x].basedOn}}': '{{formatWhole(tmp.skills[x].xpGain)}} 经验 (下一个在 {{format(nextXP(x))}} {{skill_data[x].basedOn}}',
    '\t\t\tThe Energy mechanic works like this: You generate 1 Base Energy/sec, then it\'s raised to the power of the exponent shown.': '\t\t\t能量机制的工作原理是这样的：你每秒产生 1 基础能量，然后增加到所示指数的幂。',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Increase the Energy exponent by ": "将能源指数提高 ",
    "Increase the above upgrade\'s effect by ": "提升以上升级效果 ",
    "Level: ": "等级: ",
    "Energy increases its exponent by ": "能源将其指数增加 ",
    "Karma: ": "业力：",
    "Req: Energy exponent of ": "要求：能量指数",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    'ON': '打开',
    'OFF': '关闭',
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Cost: (.+) Energy$/, '成本: $1 能源'],
    [/^Cost: (.+) Mega-Energy$/, '成本: $1 巨型能源'],
    [/^Cost: (.+) Hyper-Energy$/, '成本: $1 超超级能源'],
    [/^Cost: (.+) Super-Energy$/, '成本: $1 超级能源'],
    [/^Super-Energy adds (.+) free levels to the above upgrade.$/, '超级能量增加了 $1 免费等级针对以上升级。'],
    [/^\t\tNext Feature: Requires (.+) Super-Energy. \((.+)$/, '\t\t下一个功能：需要 $1 超级能源。 \($2'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);