/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    'Info': '信息',
    'levels to the first 3 Energy Upgrades.': '升级到前 3 次能源升级。',
    'Main': '首页',
    'Mega-Energy': '兆级能源',
    'Options': '选项',
    'Super': '超级',
    'Super Drives': '超级驱动器',
    'Super-Energy': '超级能源',
    'Superchargers': '超级充电器',
    'weaker, and adds': '较弱，并增加',
    'Self-Charging Batteries': '自充电电池',
    ', which adds': '，增加',
    ', which makes Energy Overflow': '，这就产生了能源溢出',
    '\t\tYou have': '\t\t你有',
    '\t\t\tYou have split': '\t\t\你分裂了',
    '\t\t\t\tYour best Energy exponent in an Unfortunate run is': '\t\t\t\t你在不幸运行中的最佳能源指数是',
    '\t\t\t\tYou have': '\t\t\t\t你有',
    'Archaic Processors': '古老的处理器',
    'atoms, which adds': '原子，这增加了',
    'Chargers': '充电器',
    'Currently': '当前',
    'Energy': '能源',
    'Reset Hyper Upgrades': '重置究级升级',
    'Sacrifice all previous progress to build a Mega Factory.': '牺牲之前的所有进度来建造超级工厂。',
    'and reduce the Mega Energy effect softcap\'s power by': '并通过以下方式降低 兆级能源 效果 软上限 的功率',
    'to all previous Energy exponents.': '到所有以前的能源指数。',
    'to the Energy & Super-Energy exponents.': '到能源和超级能源指数。',
    'to the Fortune Energy exponent.': '到财富能源指数。',
    'to the Hyper-Energy exponent.': '到究级能源指数。',
    'Hyper-Energy': '究级能源',
    'Fortune Energy': '财富能源',
    'Galvanic Compressors': '电流压缩机',
    'Gifts, which multiply the Fortune Energy exponent by': '礼物，将财富能源指数乘以',
    'Supercharge your Energy to gain {{formatWhole(tmp.sup.gain)}} base Super-Energy, and to increase the Super-Energy exponent by {{format(tmp.sup.expInc)}}.': '增压你的能源以获得 {{formatWhole(tmp.sup.gain)}} 基础超级能源，并将超级能源指数增加 {{format(tmp.sup.expInc)}}。',
    'You have supercharged your Energy {{formatWhole(player.sup.times)}} times.': '你已经将你的能源增压 {{formatWhole(player.sup.times)}} 次。',
    'WARNING: Each Hyper Upgrade level decreases the Hyper-Energy exponent by {{format(tmp.hyper.upgDecExp)}}. (Currently: -{{format(tmp.hyper.totalUpgs.times(tmp.hyper.upgDecExp))}}': '警告：每个究级升级级别都会将兆级能源指数降低 {{format(tmp.hyper.upgDecExp)}}。 （目前：-{{format(tmp.hyper.totalUpgs.times(tmp.hyper.upgDecExp))}}',
    '\t\t\tYou have': '\t\t\t你有',
    'Due to Energy Overflow, your Energy is being divided by {{format(tmp.en.divPerSec)}} every second.': '由于能源溢出，你的能源每秒除以 {{format(tmp.en.divPerSec)}}。',
    '{{formatWhole(tmp.skills[x].xpGain)}} XP (next at {{format(nextXP(x))}} {{skill_data[x].basedOn}}': '{{formatWhole(tmp.skills[x].xpGain)}} 经验 (下一个在 {{format(nextXP(x))}} {{skill_data[x].basedOn}}',
    '\t\t\tThe Energy mechanic works like this: You generate 1 Base Energy/sec, then it\'s raised to the power of the exponent shown.': '\t\t\t能源机制的工作原理是这样的：你每秒产生 1 基础能源，然后增加到所示指数的幂。',
    'Mega': '兆级',
    'Holy Destroyers': '神圣毁灭者',
    'Positive Karma = Higher chance of getting more Gifts. Negative Karma = Higher chance of getting less Gifts.': '正业力 = 获得更多礼物的机会更高。 负业力 = 获得更少礼物的机会更高。',
    'Put all your Energies into the Hypertube to split {{formatWhole(tmp.hyper.gain)}} atoms.': '将你所有的能源放入究级管以分裂 {{formatWhole(tmp.hyper.gain)}} 原子。',
    'Req: {{formatWhole(fortune_req)}} Fortune Energy.': '要求: {{formatWhole(fortune_req)}} 财富能源.',
    'True Souls': '真正的灵魂',
    'Voltaic Conductors': '光伏导线',
    'Auto': '自动',
    'You have put all your energies into the Hypertube {{formatWhole(player.hyper.times)}} times.': '你已经把所有的能源都投入到究级管 {{formatWhole(player.hyper.times)}} 次。',
    'Automated Archaic Processors': '自动化古老处理器',
    'Automated Chargers': '自动化充电器',
    'Automated Galvanic Compressors': '自动化电流压缩机',
    'Automated Heroic Stones': '自动化英雄石',
    'Automated Holy Destroyers': '自动化神圣毁灭者',
    'Automated Mega Organic Tellers': '自动化兆级有机柜员机',
    'Automated Mega Trophies': '自动化兆级奖杯',
    'Automated Organic Tellers': '自动化有机柜员',
    'Automated Power Plants': '自动化发电厂',
    'Automated Prestige Cities': '自动化声望城市',
    'Automated Self-Charging Batteries': '自动化自充电电池',
    'Automated Super Drives': '自动化超级驱动器',
    'Automated Super-Energy exponent gain': '自动化超级能源指数增益',
    'Automated Superchargers': '自动化增压器',
    'Automated True Souls': '自动化真正的灵魂',
    'Automated Voltaic Conductors': '自动化光伏导线',
    'Organic Tellers': '有机柜员',
    'Power Plants': '发电厂',
    'Prestige Cities': '声望城市',
    'Prestigeless Power': '无声望力量',
    'Prestige Cities boost themselves.': '声望城市自我提升。',
    'Purged Heroes': '清除英雄',
    'Self-Charging Batteries & Holy Destroyers are boosted by your Mega-Energy.': '自充电电池和神圣毁灭者由您的兆级能源增强。',
    'Skill Levels require less XP based on your Energy exponent.': '根据您的能源指数，技能等级需要更少的 经验。',
    'Skill Plus': '技能+',
    'Skill XP adds to the Energy, Super-Energy, & Mega-Energy exponents.': '技能 经验 添加到能源、超级能源和兆级能源指数中。',
    'Skills': '技能',
    'The first two Skills gain more XP based on your Mega Factories.': '前两个技能根据您的超级工厂获得更多 经验。',
    'Anti-Slowdown Measures': '防减速措施',
    'Antitrust Energy': '反垄断能源',
    'Buy max Energy Upgrades, and add 0.5 to Mega-Energy exponent for each Mega Upgrade.': '购买最大能源升级，并为每个超级升级增加 0.5 到超级能源指数。',
    'Dirt Regime': '污垢制度',
    'Energy Overflow starts 1e10x later for every Energy Upgrade level.': '能源溢出在每一次能源升级的1e10倍之后开始。',
    'Excess Explosion': '过度爆炸',
    'False Denial': '虚假否认',
    'Experienced Ancient': '经验老者',
    'Haven of Gods': '神的天堂',
    'Increase the Mega Energy exponent by 0.02 for every Super Upgrade level.': '超级升级每升一级，兆级能源指数增加 0.02。',
    'Mega Evolution': '兆级进化',
    'Mega Factories add to the first 6 Super Upgrade effects.': '兆级工厂添加到前 6 个超级升级效果。',
    'Mega Factories boost the base Super-Energy exponent.': '兆级工厂提升基础超级能源指数。',
    'Heroic Stones': '英雄石',
    'Mega Organic Tellers': '兆级有机柜员',
    'Mega Trophies': '兆级奖杯',
    'Automated Mega Upgrades': '自动化兆级升级',
    'Automated Skill XP Gain': '自动化技能 经验 获得',
    'Automated Skilled Ninja': '自动化熟练忍者',
    'Automated Subatomic Generators': '自动亚原子发生器',
    'Fortune': '财富',
    'Hyper': '究级',
    'Automated Hyper Plants': '自动化究级工厂',
    'Automated Mega Factories': '自动化兆级工厂',
    'Hypercharged': '究级充电',
    'Maintained Power': '维持电力',
    'Manufactured Tellers': '人造柜员',
    'Mega Drives': '兆级驱动器',
    'Swordsmith\'s Dream': '铸剑师的梦想',
    'The Atomic Present': '原子存在',
    'The first Skill\'s effect also affects the first & third scalings, and the Super-Energy exponent is 50% higher when below 10,000.': '第一个技能的效果也影响第一个和第三个缩放，超级能源指数在10000以下时提高50%。',
    'Titanium Vessels': '钛制容器',
    'Unfazed Reactions': '冷静的反应',
    'Uranium Vessels': '铀容器',
    'Uranium Vessels are stronger based on their level.': '铀容器的强度取决于它们的等级。',
    'Accelerated Neutrinos': '加速中微子',
    'Broken Particles': '破碎粒子',
    'Destroy 1 Fortune Energy to get gifts!': '摧毁1个财富能源获得礼物!',
    'Exit this Unfortunate run.': '退出这个不幸的运行。',
    'Start an Unfortunate run, which square roots all Energy exponents.': '开始一个不幸的运行，它对所有能源指数进行平方根。',
    'Mega Factories boost Split Atom & Gift gain.': '兆级工厂促进分裂原子和礼物增益。',
    'Hyper Luck': '究级幸运',
    'Hyper End': '究级终点',
    'Gift Power': '礼物力量',
    'Fortune Energy adds to the Hyper-Energy exponent & to Karma.': '财富能源增加了超能源指数和业力。',
    'Fortune Energy & Gifts make Skills stronger.': '财富能源和礼物使技能更强大。',
    'Excess Nuclearity': '过剩核率',
    'Each Mega Upgrade adds 0.05 to the Hyper-Energy exponent.': '每一次兆级升级都会增加0.05的究级能源指数。',
    'Neutral Karma': '中性业力',
    'Remove the softcaps of Self-Charging Batteries & Super Drives.': '移除自充电电池和超级驱动器的软上限。',
    'Split Atoms\' effect is 25% stronger, and they add to the Fortune Energy exponent at a reduced rate.': '分裂原子的效果增强 25%，并且它们以降低的速度增加财富能源指数。',
    'Split Atoms add to the Organic Teller, Mega Organic Teller, and Hyper Plant effects.': '分裂原子添加到有机柜员, 兆级有机柜员，和究级工厂效果。',
    'Skilled Ninja': '熟练的忍者',
    'Hyper Plants': '究级工厂',
    'Getting Gifts only decreases your Fortune Energy by 1, Gift gain is increased by 50%, and the Fortune Energy exponent is increased by 0.1.': '获得礼物只会减少你的财富能源1，礼物增益增加50%，财富能源指数增加0.1。',
    'Self-Charged Batteries add to the Mega & Hyper-Energy exponents at a reduced rate.': '自充电电池添加到兆级 & 究级能源指数在一个减少的速率。',
    'All Mega Upgrades beyond the first two rows are kept on Hyper reset, and the Split Atom effect is 75% stronger.': '前两行以外的所有兆级升级都保持究级重置，分裂原子效果增强 75%。',
    'Buy max Super-Energy Upgrades, and the first softcap of all Energy Upgrades (except Self-Charging Batteries) is 20% weaker.': '购买最大超级能源升级，所有能源升级的第一个软上限（自充电电池除外）弱 20%。',
    'Subatomic Generators': '亚原子发生器',
    '{{(player.mega.upgrades.includes(19))?\"Destroy 1 Fortune Energy\":\"Destroy all your Fortune Energy\"}} to get{{(player.fortune.energy.gte(fortune_req)?(\" \"+formatWhole(tmp.fortune.minGain)+\"-\"+formatWhole(tmp.fortune.maxGain)):\"\")}} gifts!': '{{(player.mega.upgrades.includes(19))?\"摧毁1财富能源\":\"摧毁全部财富能源\"}} 去获得{{(player.fortune.energy.gte(fortune_req)?(\" \"+formatWhole(tmp.fortune.minGain)+\"-\"+formatWhole(tmp.fortune.maxGain)):\"\")}} 礼物!',
    'Goals': '目标',
    'Red Giant': '红巨星',
    'Neutron Star': '中子星',
    'Black Hole': '黑洞',
    'Does nothing': '什么都不做',
    'Sync Neutron Star Cooldowns': '同步中子星冷却时间',
    'Ultra-Energy': '终级能源',
    '& multiplies the Unfortunate run effect by': '& 将不幸的运行效果乘以',
    'Constellations': '星座',
    'Darkness, which multiplies Atom & Gift gain by': '黑暗，将原子和礼物增益乘以',
    'Next Star at {{formatWhole(STAR_UNLOCKS[tmp.const.starsCanUnl])}} Darkness': '下一个星球在 {{formatWhole(STAR_UNLOCKS[tmp.const.starsCanUnl])}} 黑暗',
    'Star Energy': '星能源',
    'Star': '星星',
    'Mega Resurgence does not force a Hyper reset when bought, and its effect also adds to the Fortune Energy exponent {{ultraChoice(6, 1)?\"(SELECTED)\":\"\"}}': '超级复兴 在购买时不会强制超级重置，而且它的效果还会增加财富能源指数 {{ultraChoice(6, 1)?\"(已选择)\":\"\"}}',
    'Add 0.5 to the Ultra-Energy exponent {{ultraChoice(7, 2)?\"(SELECTED)\":\"\"}}': '将 0.5 添加到 终级能源 指数 {{ultraChoice(7, 2)?\"(已选择)\":\"\"}}',
    'Completed Goals: {{player.hideComplGoals?\"HIDDEN\":\"SHOWN\"}}': '已完成目标: {{player.hideComplGoals?\"隐藏\":\"显示\"}}',
    'Reset all previous progress to gain {{formatTime(tmp.ultra.gain)}} worth of Ultra-Energy.': '重置所有之前的进度以获得 {{formatTime(tmp.ultra.gain)}} 价值的终级能源。',
    'All Energy Upgrades are 59% stronger {{ultraChoice(8, 1)?\"(SELECTED)\":\"\"}}': '所有能源升级都增强了 {{ultraChoice(8, 1)?\"(已选择)\":\"\"}}',
    'Evolved Amoebas also affect the Mega-Energy exponent {{ultraChoice(2, 2)?\"(SELECTED)\":\"\"}}': '进化的变形虫也会影响兆级能源指数 {{ultraChoice(2, 2)?\"(已选择)\":\"\"}}',
    'Holy Destroyers are 900% stronger {{ultraChoice(7, 1)?\"(SELECTED)\":\"\"}}': '神圣毁灭者增强 900% {{ultraChoice(7, 1)?\"(已选择)\":\"\"}}',
    'Ultra': '终级',
    'The first Skill\'s XP gain is multiplied by Star Energy {{ultraChoice(4, 1)?\"(SELECTED)\":\"\"}}': '第一个技能的 经验 增益乘以 星能源 {{ultraChoice(4, 1)?\"(已选择)\":\"\"}}',
    'The first 3 rows of Ultra upgrades are always selected {{ultraChoice(6, 2)?\"(SELECTED)\":\"\"}}': '终级升级的前3行总是被选中{{ultraChoice(6, 2)?\"(已选择)\":\"\"}}',
    'Karma is increased by 25% & Gift RNG is exponential {{ultraChoice(4, 2)?\"(SELECTED)\":\"\"}}': '业力 增加 25% & 礼物 RNG 是指数的 {{ultraChoice(4, 2)?\"(已选择)\":\"\"}}',
    'Karma Range: {{format(tmp.fortune.addKarma.sub(1).times(100))}}% to {{format(tmp.fortune.addKarma.plus(1).times(100))}}': '业力范围：{{format(tmp.fortune.addKarma.sub(1).times(100))}}% 到 {{format(tmp.fortune.addKarma.plus(1).times(100))}}',
    'Mega Factory cost scales 75% slower {{ultraChoice(1, 2)?\"(SELECTED)\":\"\"}}': '兆级工厂成本增加 75% {{ultraChoice(1, 2)?\"(已选择)\":\"\"}}',
    'Multiply Skilled Ninja\'s effect by the Ultra-Energy exponent {{ultraChoice(5, 2)?\"(SELECTED)\":\"\"}}': '将熟练忍者的效果乘以终级能源指数 {{ultraChoice(5, 2)?\"(已选择)\":\"\"}}',
    'Multiply Super Drives\' effect by the Star Energy exponent {{ultraChoice(5, 1)?\"(SELECTED)\":\"\"}}': '将 超级驱动器 的效果乘以 星能源 指数 {{ultraChoice(5, 1)?\"(已选择)\":\"\"}}',
    'Star Energy exponent is increased by {{format(neutronStarEff())}} for {{format(Math.max(player.constellations.stars[player.constellations.selected].time-neutronStarCooldownTime(), 0))}} seconds{{(player.constellations.stars[player.constellations.selected].time>0&&player.constellations.stars[player.constellations.selected].time<=neutronStarCooldownTime())?(\" (cooldown: \"+format(player.constellations.stars[player.constellations.selected].time)+\" seconds)\"):\"\"}}': '星能源指数增加 {{format(neutronStarEff())}} {{format(Math.max(player.constellations.stars[player.constellations.selected].time-neutronStarCooldownTime(), 0))}} 秒 {{(player.constellations.stars[player.constellations.selected].time>0&&player.constellations.stars[player.constellations.selected].time<=neutronStarCooldownTime())?(\"（冷却时间：\"+format( player.constellations.stars[player.constellations.selected].time)+\" 秒)\"):\"\"}}',
    'Star Energy is halved every second, but you gain Darkness from lost Star Energy': '星能源每秒减半，但你会从失去的星能源中获得黑暗',
    'You can gain more than 1s worth of Ultra-Energy on reset {{ultraChoice(2, 1)?\"(SELECTED)\":\"\"}}': '可以获得超过 1 秒的终级能源通过重置 {{ultraChoice(2, 1)?\"(已选择)\":\"\"}} ',
    'You have performed {{formatWhole(player.ultra.times)}} Ultra resets, which increases the Ultra-Energy exponent by {{format(tmp.ultra.timesEff)}}': '您已经执行了 {{formatWhole(player.ultra.times)}} 终级重置，这将 终级能源 指数增加了 {{format(tmp.ultra.timesEff)}}',
    'Progress: {{hasGoal(x)?\"COMPLETE\":(format(Decimal.mul(goal_data[x].progress(), 100))+\"%\")}}': '进度：{{hasGoal(x)?\"完成\":(format(Decimal.mul(goal_data[x].progress(), 100))+\"%\")}}',
    'Neutron Star cooldown is reduced by 4s {{ultraChoice(3, 2)?\"(SELECTED)\":\"\"}}': '中子星冷却时间减少 4s {{ultraChoice(3, 2)?\"(已选择)\":\"\"}}',
    ', and adds': ',并增加',
    ', which multiplies the Normal, Super, Mega, & Hyper Energy exponents by': '，它将 普通、超级、兆级 和 究级 能源 指数乘以',
    '# of Hyper resets multiplies Super resets gained {{ultraChoice(1, 1)?\"(SELECTED)\":\"\"}}': '# 兆级重置的数量乘以超级重置获得的{{ultraChoice(1, 1)?\"(已选择)\":\"\"}}',
    '# of Ultra resets multiplies Hyper resets gained {{ultraChoice(3, 1)?\"(SELECTED)\":\"\"}}': '# 终级重置次数乘以获得究级重置次数 {{ultraChoice(3, 1)?\"(已选择)\":\"\"}}',
    'Rows 4 & 5 of Ultra upgrades are always selected {{ultraChoice(8, 2)?\"(SELECTED)\":\"\"}}': '始终选择 终级 升级的第 4 和 5 行 {{ultraChoice(8, 2)?\"(已选择)\":\"\"}}',
    'Star Energy exponent is increased by {{format(redGiantEff())}}': '星能源指数增加 {{format(redGiantEff())}}',
    'Energy, Super-Energy, Mega-Energy, & Hyper-Energy exponents are increased by 20%.': '能源、超级能源、兆级能源和终级能源指数增加 20%。',
    'Hypernova': '超新星',
    'Hypertube Acceleration': '超管加速',
    'Mega Resurgence': '超级复兴',
    'Mega Upgrades each add 6 to the Mega-Energy exponent, but Mega Upgrade rows 3 & 4 will always reset on Hyper reset (buying/toggling this forces a Hyper reset).': '兆级升级每次都会为兆级能源指数增加 6，但兆级升级第 3 行和第 4 行将始终在究级重置时重置（购买/切换这会强制究级重置）。',
    'Multiply Red Giant, Neutron Star, & Darkness effects based on Energy exponent, & unlock 3 new Hyper Upgrades.': '根据能源指数乘以红巨星、中子星和黑暗效果，并解锁 3 个新的究级升级。',
    'Net Intensity': '净强度',
    'Neutron Star cooldown is reduced by 10s, and triple Skill levels gained.': '中子星冷却时间缩短 10 秒，技能等级提升三倍。',
    'Star Energy has its own effect.': '星能源有其自身的作用。',
    'Star Power': '星力',
    'Supernova': '超新星',
    'Hypernova': '究级新星',
    'Add 1.50 free levels to all previous Hyper Upgrades.': '为之前的所有究级升级添加 1.50 个免费级别。',
    'Atomic Eruptions': '原子爆发',
    'Concentrated Plutonium': '浓缩钚',
    'Electric Presents': '电子礼物',
    'Evolved Amoebas': '进化的变形虫',
    'Gravity Pillars': '重力柱',
    'Increase the Mega & Hyper-Energy exponents by 50.00': '将 兆级 和 究级能源 指数增加 50.00',
    'Increase the Mega-Energy effect by 1,750% (based on upg level': '将 兆级能源 效果提高 1,750%（基于升级等级',
    'Nuclear Strings': '核弦',
    'Multiply the upper limit of Gift gain by 20.00': '礼物获得上限乘以20.00',
    ', which reduces the second Hyper-Energy effect\'s softcap by': '，这将第二个 究级能源 效果的 软上限 减少',
    '# of Hyper resets multiply Atom gain.': '# 的究级重置乘以 原子 增益。',
    'Auto-Select Neutron Stars': '自动选择中子星',
    'Automated Hyper Upgrades': '自动究级升级',
    'Best Energy Exponent in Unfortunate Run is always gained': '不幸奔跑中的最佳能源指数总是获得',
    'Aging Necessity': '老化的必要性',
    'Agonizing Rock': '痛苦的岩石',
    'All Charged Up!': '全部充电！',
    'Are We The FBI or Something?': '我们是联邦调查局还是什么？',
    'Army of the Heavens': '天界大军',
    'Artificial Holder': '人工支架',
    'Atomic Entropy': '原子熵',
    'Clicking Is Now Useless!': '点击现在没用了！',
    'Compressed into Nothing': '压缩成空',
    'Energy But Worse': '能源但更糟',
    'Energy Acceleration': '能源加速',
    'Energy Upgrades Go Brrrrrrrrrr': '能源升级到Brrrrrrrrrr',
    'EnerJerk™': '能源混蛋™',
    'Excitement To The Highest Level': '兴奋到最高等级',
    'Four Twos For Two Fore Tools': '四个2，用于两个前工具',
    'Halfway To Conspiracy': '阴谋半途而废',
    'How Unfortunate!': '多么的不幸！',
    'I\'m Too Old For This': '我太老了',
    'Infinite Power': '无限力量',
    'Intense Powers': '强大的力量',
    'It Has Begun': '已经开始了',
    'It Has Begun (again': '已经开始了 (再次',
    'Joule Multiplication': '焦耳乘法',
    'Just a noob with time on their hands, right?': '只是一个手上有时间的菜鸟，对吧？',
    'Ohm I! You Shouldn\'t Be Here!': '哦我！ 你不应该在这里！',
    'Overcharged Field': '过充电场',
    'Owie!': '欧喂！',
    'Potential Kilobyte!': '潜在的KB！',
    'Potential Megabyte!!': '潜在MB！！',
    'Potential Octobyte?': '潜在的OB？',
    'Potential Petabyte!!!': '潜在的PB ！！！',
    'Put it into Superdrive?': '把它放进超级驱动器？',
    'Req: Start gaining Supercharged resets passively.': '要求：开始被动获得超级充电器重置。',
    'Req: Reduce Energy Overflow to 0.1% of its original power.': '要求：将能源溢出减少到其原始功率的 0.1%。',
    'RNG Means Nothing!': 'RNG 没有任何意义！',
    'Sealed Container': '密封容器',
    'Smoke Billows In The Air': '烟雾缭绕',
    'Still A Noob...': '还是菜鸟...',
    'Super Annihilator': '超级歼灭者',
    'Super Destroyer': '超级毁灭者',
    'Super Maniac': '超级疯子',
    'This Is All Of Them... Right???': '这就是他们的全部…对吧? ?',
    'Watt Are You Doing?': '你在做什么?',
    'We Did Not Build This City': '我们没有建造这座城市',
    'Well Isn\'t This Familiar...': '嗯，这不是很熟悉吗...',
    'What Does This Even Mean???': '这到底是什么意思？？？',
    'What Does This Have To Do With Energy?': '这与能源有什么关系？',
    'Woah That\'s Some Chad Energy': '哇，那是一些乍得能源',
    'Woah This Is Nuts!': '哇，这是坚果！',
    'Woah, Stop Getting Me Amped!': '哇，别让我兴奋了！',
    'Wow You Died At Level 4? Noob.': '哇你死在第 4 级？ 小白。',
    'Req: Purchase 555 Super Drives.': '要求：购买 555 个超级驱动器。',
    'Req: Perform 1e25 Super resets.': '要求：执行 1e25 超级重置。',
    'Req: Get 144,000 extra Galvanic Compressors.': '要求：获得 144,000 台额外的电流压缩机。',
    'Req: Gain 69.00s of Ultra-Energy in one reset.': '要求：在一次重置中获得 69.00 秒的终级能源。',
    '\t\t\tGoals': '\t\t\t目标',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Increase the Energy exponent by ": "将能源指数提高 ",
    "Increase the above upgrade\'s effect by ": "提升以上升级效果 ",
    "Level: ": "等级: ",
    "Energy increases its exponent by ": "能源将其指数增加 ",
    "Karma: ": "业力：",
    "Req: Energy exponent of ": "要求：能源指数",
    "Mega Factories increase the effects of both above upgrades by ": "兆级工厂增加了上述两种升级的效果",
    "Mega Factories, which increase the Mega-Energy exponent by": "兆级工厂，将 兆级能源 指数增加",
    "Self-Charging Batteries increase their effect by ": "自充电电池增加其效果",
    "\t\tNext Feature: Requires an Energy exponent of ": "\t\t下一个功能：需要能源指数为",
    "Galvanic Compressors increase the Super-Energy exponent by ": "电流压缩机将兆级能源指数增加",
    "Mega-Energy: ": "兆级能源：",
    "Super-Energy: ": "超级能源: ",
    "The Mega-Energy effect uses a better formula (": "兆级能源 效果使用了一个更好的公式（",
    "Energy: ": "能源: ",
    "\t\tYou have reached the end! (": "\t\你已经到了终点！ (",
    "Hyper: ": "究级: ",
    "Hyper-Energy increases the Super-Energy exponent by ": "究级能源 将 超级能源 指数增加",
    "Split atoms subtract the Mega Factory requirement by ": "分裂原子减去兆级工厂要求",
    "Mega: ": "兆级: ",
    "Ultra-Energy increases the Split Atom & Mega Factory effect exponents by ": "究级能源 将 分裂原子 和 兆级工厂 效果指数增加了",
    "Unlocked Stars increase Split Atom gain & effect exponents by ": "解锁的星星使分裂原子增益和效果指数增加",
    "Nice": "不错",
    "Req: Reach a Super-Energy effect of ": "要求：达到超级能源效果",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    'ON': '打开',
    'OFF': '关闭',
    " Base Super-Energy/sec": " 基础超级能源/秒",
    " reset of Supercharged resets/sec": " 重置增压重置/秒",
    " Gift clicks/sec": "礼物点击/秒",
    " reset of Hyper resets/sec": "重置究级重置/秒",
    " of Atom Gain/sec": "原子增益/秒",
    " of Darkness Gain/sec": "黑暗增益/秒",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^成本: (.+) 能源$/,
    /^由于能源溢出，你的能源每秒除以 (.+)。$/,
    /^业力：(.+)$/,
    /^([\d\.,]+)$/,
    /^e([\d\.,]+)$/,
    /^e([\d\.,]+)x$/,
    /^\+([\d\.,]+)$/,
    /^([\d\.]+)x$/,
    /^([\d\.,])x$/,
    /^([\d\.,])x$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\d\.]+)$/,
    /^等级: (.+)$/,
    /^摧毁1财富能源 去获得 (.+) 礼物!$/,
    /^重置所有之前的进度以获得 (.+) 价值的终级能源。$/,
    /^你已经把所有的能源都投入到究级管 (.+) 次。$/,
    /^将你所有的能源放入究级管以分裂 (.+) 原子。$/,
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+)\% stronger$/, '$1\% 强'],
    [/^([\d\.,]+)\% stronger$/, '$1\% 强'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Super-Energy multiplies XP gain by (.+).$/, '超级能源将 XP 增益乘以 $1。'],
    [/^Power Plants are (.+)\% stronger.$/, '发电厂要强 $1\%。'],
    [/^Split atoms add (.+) to the Super-Energy exponent.$/, '分裂原子将超级能源指数加 $1。'],
    [/^The (.+) of times supercharged adds (.+) to the Super-Energy effect.$/, '$1次 增压增加 $2 的超级能源效果。'],
    [/^The 2nd Energy Upgrade's cost increases (.+)\% slower$/, '第二能源升级的成本增长速度降低了 $1\%'],
    [/^The first 3 Energy Upgrade costs are extended by (.+) levels.$/, '前 3 次能源升级费用扩展 $1 级。'],
    [/^The Super-Energy effect softcap is (.+)\% weaker$/, '超级能源效应软上限变弱 $1\%'],
    [/^(.+)Level: (.+) \(Next: (.+) more XP$/, '等级：$2（下一个：$3 经验'],
    [/^Mega Factories are (.+)\% more efficient$/, '兆级工厂的效率提高了 $1\%'],
    [/^(.+) 经验 \(下一个在 (.+) Super-Energy$/, '$1 经验 \(下一个在 $2 超级能源'],
    [/^(.+) 经验 \(下一个在 (.+) Mega-Energy$/, '$1 经验 \(下一个在 $2 兆级能源'],
    [/^Energy adds (.+) to the Super-Energy exponent.$/, '能源将超级能源指数增加 $1。'],
    [/^Get (.+) more supercharged resets on each Super reset.$/, '每次超级重置获得 $1 次以上的增压重置。'],
    [/^The first (.+) Energy Upgrade costs are extended by (.+) levels.$/, '前 $1 次能源升级费用增加 $2 级。'],
    [/^Mega Energy adds (.+) levels to the first (.+) Super Upgrades.$/, '兆级能源 为前 $2 个超级升级增加了 $1 级。'],
    [/^Mega Factories add (.+) levels to all Energy upgrades.$/, '兆级工厂为所有能源升级增加 $1 级。'],
    [/^Req: ([\d\.,]+) Ultra-Energy$/, '需要: $1 终级能源.'],
    [/^Req: ([\d\.,]+) Hyper-Energy.$/, '需要: $1 究级能源.'],
    [/^Req: ([\d\.]+)e([\d\.,]+) Hyper-Energy.$/, '需要: $1e$2 究级能源.'],
    [/^Req: ([\d\.]+)e([\d\.,]+) Hyper-Energy$/, '需要: $1e$2 究级能源'],
    [/^Req: Reach (.+) Hyper-Energy.$/, '需要: 达到 $1 究级能源.'],
    [/^Req: Reach (.+) Mega-Energy.$/, '需要: 达到 $1 兆级能源.'],
    [/^Req: Reach (.+) Super-Energy.$/, '需要: 达到 $1 超级能源.'],
    [/^Req: Reach (.+) Mega Factories.$/, '需要: 达到 $1 兆级工厂.'],
    [/^Req: Reach (.+) Darkness.$/, '需要: 达到 $1 黑暗.'],
    [/^Req: Reach (.+) Energy.$/, '需要: 达到 $1 能源.'],
    [/^Req: Reach (.+) Gifts.$/, '需要: 达到 $1 礼物.'],
    [/^Req: Reach (.+) Atoms.$/, '需要: 达到 $1 原子.'],
    [/^Req: Reach Level (.+) in each Skill.$/, '需要: 每个技能达到 $1 级.'],
    [/^Req: Reach a Mega-Energy exponent of (.+).$/, '需要: 达到兆级能源指数 $1.'],
    [/^Req: Reach a Super-Energy exponent of (.+).$/, '需要: 达到超级能源指数 $1.'],
    [/^Req: Reach an Energy exponent of (.+) within an Unfortunate run.$/, '需要: 达到能源指数 $1 在不幸的运行中。'],
    [/^Req: Reach an Energy exponent of (.+).$/, '需要: 达到能源指数 $1.'],
    [/^Req: Perform (.+) Super Resets.$/, '需要: 购买 $1 超级重置.'],
    [/^Req: Purchase (.+) Supercharger.$/, '需要: 购买 $1 超级充电器.'],
    [/^Req: Purchase (.+) Super Drive.$/, '需要: 购买 $1 超级驱动.'],
    [/^Req: Purchase (.+) Archaic Processor.$/, '需要: 购买 $1 古老的处理器.'],
    [/^Req: Purchase (.+) Organic Teller.$/, '需要: 购买 $1 有机柜员.'],
    [/^Req: Purchase (.+) SSuper Drive.$/, '需要: 购买 $1 超级驱动.'],
    [/^Req: Purchase (.+) Skilled Ninja.$/, '需要: 购买 $1 熟练的忍者.'],
    [/^Req: Purchase (.+) Self-Charging Battery.$/, '需要: 购买 $1 自充电电池.'],
    [/^Req: Purchase (.+) Prestige City.$/, '需要: 购买 $1 声望之城.'],
    [/^Req: Purchase (.+) Holy Destroyer.$/, '需要: 购买 $1 神圣毁灭者.'],
    [/^Req: Purchase (.+) Heroic Stone.$/, '需要: 购买 $1 英雄石.'],
    [/^Req: Purchase (.+) Galvanic Compressor.$/, '需要: 购买 $1 电流压缩机.'],
    [/^Req: Purchase (.+) Charger.$/, '需要: 购买 $1 充电器.'],
    [/^Req: Purchase (.+) Voltaic Conductors.$/, '需要: 购买 $1 光伏导线.'],
    [/^Req: Purchase (.+) Voltaic Conductor.$/, '需要: 购买 $1 光伏导线.'],
    [/^Req: Purchase (.+) Mega Upgrades.$/, '需要: 购买 $1 兆级升级.'],
    [/^Req: Purchase (.+) True Soul.$/, '需要: 购买 $1 真正的灵魂.'],
    [/^Req: Purchase (.+) Self-Charging Batteries.$/, '需要: 购买 $1 自充电电池.'],
    [/^\t\tNext Feature: Requires (.+) Hyper-Energy. \((.+)$/, '\t\t下一个功能：需要 $1 究极能量。 \($2'],
    [/^Cost: (.+) Energy$/, '成本: $1 能源'],
    [/^Cost: (.+) Energy$/, '成本: $1 能源'],
    [/^Cost: (.+) Mega-Energy$/, '成本: $1 兆级能源'],
    [/^Cost: (.+) Hyper-Energy$/, '成本: $1 究级能源'],
    [/^Cost: (.+) Super-Energy$/, '成本: $1 超级能源'],
    [/^Super-Energy adds (.+) free levels to the above upgrade.$/, '超级能源增加了 $1 免费等级针对以上升级。'],
    [/^\t\tNext Feature: Requires (.+) Super-Energy. \((.+)$/, '\t\t下一个功能：需要 $1 超级能源。 \($2'],
    [/^\t\tNext Feature: Requires (.+) Mega Factories. \((.+)$/, '\t\t下一个功能：需要 $1 兆级工厂。 \($2'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);